### ISSUE TITLE
Roadmap for further work on data-manager

### ISSUE THREAD

**Issue by sg-s** [sg-s/data-manager#5]
- [ ] DataManager.py can hash files
- [ ] DataManager.py can remember hash tables, and reload them when called
- [ ] DataManager.py respects dmignore.m
- [ ] python implementation of data-manager reaches feature parity with MATLAB implementation 
- [ ] DataManager.py can be called from the command line externally of python 
- [ ] MATLAB version deprecated, rewritten as a wrapper around the python version.
